---
title: "MSK SPECTRUM data freeze: major cell type embeddings"
author: "Florian Uhlitz"
date: "`r Sys.Date()`"
output: 
  html_document: 
    df_print: kable
    number_sections: yes
    toc: yes
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = F)

```

```{r chunk_010}

library(magrittr)
library(tidyverse)
library(Seurat)
library(readxl)
library(cowplot)
library(colorblindr)
library(viridis)
library(magick, lib.loc = "/home/uhlitzf/miniconda3/lib/R/library")
library(ggpubr)

```

```{r chunk_020}

## load global vars: 
source("_src/global_vars.R")

# meta_tbl
# clrs
# markers_v6
# markers_v6_super
# cell_type_super_lookup

```

```{r chunk_040}

## load full seurat objects with expression data
# seu_obj_tc <- read_rds("/work/shah/uhlitzf/data/SPECTRUM/freeze/v5/T.cell_processed_filtered_sub.rds")
# seu_obj_cc <- read_rds(paste0("/work/shah/uhlitzf/data/SPECTRUM/freeze/v5/Ovarian.cancer.cell_processed_filtered.rds"))
seu_obj_cc <- read_rds("/work/shah/uhlitzf/data/SPECTRUM/freeze/v6/Ovarian.cancer.cell_processed_filtered.rds")
markers_tbl <- read_tsv("/work/shah/uhlitzf/data/SPECTRUM/freeze/v6/Ovarian.cancer.cell_highqc_markers_02.tsv")

# plot_data <- FetchData(seu_obj_cc, c("sample", grep("^HLA", rownames(seu_obj_cc), value = T))) %>%
#   as_tibble() %>% 
#   gather(gene, value, -sample) %>% 
#   left_join(meta_tbl, by = "sample") %>% 
#   group_by(consensus_signature, gene, sample, patient_id_short) %>% 
#   summarise(value = median(value))
# 
# ggplot(plot_data) + 
#   geom_tile(aes(sample, gene, fill = value)) +
#   scale_fill_viridis() +
#   facet_grid(~consensus_signature, scales = "free_x", space = "free_x")

```

```{r chunk_050}

plot_data <- cbind(cell_id = colnames(seu_obj_cc), FetchData(seu_obj_cc, c("umapharmony_1", "umapharmony_2", "umappca_1", "umappca_2", "RNA_snn_res.0.2", "sample", "cluster_label", grep("pathway", colnames(seu_obj_cc@meta.data), value = T)))) %>% 
  as_tibble() %>% 
  left_join(meta_tbl, by = "sample") %>% 
  filter(!is.na(consensus_signature))

base_umap <- ggplot(plot_data) +
  coord_fixed() +
  NoAxes() +
  theme(legend.position = c(0, 1),
        legend.justification = c("left", "top"),
        legend.box.just = "left",
        legend.margin = margin(1, 1, 1, 1),
        #panel.border = element_rect(linetype = 1, color = "black", size = 1),
        legend.text = element_text(size = 14, margin = margin(0, 10, 0, 0)),
        legend.spacing.x = unit(0, "npc"), 
        legend.title = element_blank(),
        plot.title = element_text(hjust = 0.5, vjust = 0.5, face = "plain", size = 22))

arrow <- arrow(angle = 20, type = "closed", length = unit(0.1, "npc"))
umap_coord_anno <- ggplot(tibble(group = c("UMAP1", "UMAP2"),
                                 x = c(0, 0), xend = c(1, 0),
                                 y = c(0, 0), yend = c(0, 1),
                                 lx = c(0.5, -0.15), ly = c(-0.15, 0.5),
                                 angle = c(0, 90))) +
  geom_segment(aes(x, y, xend = xend, yend = yend, group = group),
               arrow = arrow, size = 1, lineend = "round") +
  geom_text(aes(lx, ly, label = group, angle = angle), size = 4) +
  theme_void() +
  coord_fixed(xlim = c(-0.3, 1), ylim = c(-0.3, 1))

add_umap_coord <- function(gg_obj) {
  p <- ggdraw() + 
    draw_plot(gg_obj, x = 0, y = 0, width = 1, height = 1) +
    draw_plot(umap_coord_anno, x = -0.015, y = -0.02, width = 0.2, height = 0.2)
  return(p)
}

```

```{r chunk_060}

pt.size <- 0.1
pt.size2 <- 0.2
pt.size.mini <- 0.01
pt.alpha <- 0.05
pt.alpha.mini <- 0.02

median_tbl <- plot_data %>%
  group_by(patient_id_short) %>% 
  summarise(umappca_1 = median(umappca_1), 
            umappca_2 = median(umappca_2))

umap_pca_mutsig <- base_umap + 
  geom_point(aes(umappca_1, umappca_2, color = consensus_signature), 
             size = pt.size, alpha = pt.alpha) +
  geom_text(aes(umappca_1, umappca_2, label = patient_id_short), data = median_tbl) + 
  scale_color_manual(values = clrs$consensus_signature) +
  guides(color = guide_legend(override.aes = list(size = 4, alpha = 1),
                              ncol = 1, 
                              label.position = "right")) +
  labs(title = "Mutational signature")

umap_mutsig <- base_umap + 
  geom_point(aes(umapharmony_1, umapharmony_2, color = consensus_signature), 
             size = pt.size2, alpha = pt.alpha) +
  scale_color_manual(values = clrs$consensus_signature) +
  guides(color = guide_legend(override.aes = list(size = 4, alpha = 1),
                              ncol = 1, 
                              label.position = "right")) +
  guides(color = F) + 
  labs(title = "")

umap_pca_cluster <- base_umap + 
  geom_point(aes(umappca_1, umappca_2, color = cluster_label), 
             size = pt.size, alpha = pt.alpha) +
  geom_text(aes(umappca_1, umappca_2, label = patient_id_short), data = median_tbl) + 
  scale_color_manual(values = clrs$cluster_label$Ovarian.cancer.cell) +
  guides(color = guide_legend(override.aes = list(size = 4, alpha = 1),
                              ncol = 1, 
                              label.position = "right")) +
  labs(title = "Cluster")

umap_cluster <- base_umap + 
  geom_point(aes(umapharmony_1, umapharmony_2, color = cluster_label), 
             size = pt.size2, alpha = pt.alpha) +
  scale_color_manual(values = clrs$cluster_label$Ovarian.cancer.cell) +
  guides(color = guide_legend(override.aes = list(size = 4, alpha = 1),
                              ncol = 1, 
                              label.position = "right")) +
  guides(color = F) + 
  labs(title = "")

cluster_legend <- cowplot::get_legend(umap_pca_cluster)

umap_pca_jak_stat <- base_umap + 
  # geom_point(aes(umappca_1, umappca_2), color = "grey80",
  #            size = pt.size, alpha = pt.alpha, 
  #            data = filter(plot_data, JAK.STAT.pathway <= 0)) +
  geom_point(aes(umappca_1, umappca_2, color = JAK.STAT.pathway), 
             size = pt.size, alpha = pt.alpha, 
             data = mutate(plot_data, JAK.STAT.pathway = ifelse(JAK.STAT.pathway > 4, 4, JAK.STAT.pathway))) +
  geom_text(aes(umappca_1, umappca_2, label = patient_id_short), data = median_tbl) + 
  scale_color_gradientn(colours = viridis(9), breaks = c(0, 2, 4), limits = c(min(plot_data$JAK.STAT.pathway), 4), labels = c(0, 2, "≥4")) +
  labs(title = "JAK-STAT signaling")

umap_jak_stat <- base_umap + 
  # geom_point(aes(umapharmony_1, umapharmony_2), color = "grey80",
  #            size = pt.size, alpha = pt.alpha, 
  #            data = filter(plot_data, JAK.STAT.pathway <= 0)) +
  geom_point(aes(umapharmony_1, umapharmony_2, color = JAK.STAT.pathway), 
             size = pt.size2, alpha = pt.alpha, 
             data = mutate(plot_data, JAK.STAT.pathway = ifelse(JAK.STAT.pathway > 4, 4, JAK.STAT.pathway))) +
  scale_color_gradientn(colours = viridis(9), breaks = c(0, 2, 4), limits = c(min(plot_data$JAK.STAT.pathway), 4), labels = c(0, 2, "≥4")) +
  guides(color = F) + 
  labs(title = "")

```

```{r chunk_063, fig.width=20, fig.height=5}

source("_src/comp_plot.R")

cluster_comp <- plot_data %>%
  mutate(sort_short_x = str_replace_all(sort_short, "U", "CD45-")) %>% 
  mutate(sample_id = sample) %>% 
  group_by(cluster_label, consensus_signature, sample_id, sort_short_x, tumor_supersite, therapy) %>%
  tally %>%
  group_by(consensus_signature, sample_id, sort_short_x, tumor_supersite, therapy) %>%
  mutate(nrel = n/sum(n)*100) %>%
  ungroup %>%
  mutate(cell_type = "Ovarian.cancer.cell")

plist <- default_comp_grid_list(filter(cluster_comp, sort_short_x == "CD45-"),
                                cluster_label, "Cancer.cell.3", cluster_label,
                                vec_plot = F, site_box = F, 
                                super_type = "Ovarian.cancer.cell")

pcomp_grid_p_full <- plot_grid(plotlist = plist,
                               ncol = 1, align = "v",
                               rel_heights = c(0.25, 0.25, 0.4))

pcomp_grid_p_full

```

```{r chunk_070, fig.width=20, fig.height=5}

cancer_grid_pca <- ggdraw() +
  draw_plot(add_umap_coord(umap_pca_mutsig), 
            x = 0, y = 0, width = 0.25, height = 1) +
  draw_plot(add_umap_coord(umap_pca_cluster + guides(color = F)), 
            x = 0.25, y = 0, width = 0.25, height = 1) +
  draw_grob(cluster_legend, x = 0.5, y = -0.15, height = 1) +
  draw_plot(add_umap_coord(umap_pca_jak_stat), x = 0.7, y = 0, width = 0.25, height = 1)

cancer_grid <- ggdraw() +
  draw_plot(add_umap_coord(umap_mutsig), 
            x = 0, y = 0, width = 0.25, height = 1) +
  draw_plot(add_umap_coord(umap_cluster + guides(color = F)), 
            x = 0.25, y = 0, width = 0.25, height = 1) +
  draw_plot(pcomp_grid_p_full,
            x = 0.5, y = 0, width = 0.18, height = 1) +
  draw_plot(add_umap_coord(umap_jak_stat), x = 0.7, y = 0, width = 0.25, height = 1)

cancer_grid_pca
cancer_grid

# ggsave("_fig/003_cancer_cell/003_umap_grid.pdf", cancer_grid, width = 20, height = 5)
ggsave("_fig/003_cancer_cell/003_umap_grid_pca.png", cancer_grid_pca, width = 20, height = 5)
ggsave("_fig/003_cancer_cell/003_umap_grid.png", cancer_grid, width = 20, height = 5)

```

# Differential pathway expression in cancer cells

Are there certain pathways activated in cancer cells...

* of patients with high vs low dysfunctional T cells?
* of HRD vs FBI patients

```{r chunk_090}

set.seed(42)
sampled_cell_ids <- sample(colnames(seu_obj_cc), 10000)
seu_obj_cc_sub <- subset(seu_obj_cc, cells = sampled_cell_ids)

plot_data <- FetchData(seu_obj_cc, c("umapharmony_1", "umapharmony_2", "sample", "cluster_label", grep("pathway", colnames(seu_obj_cc@meta.data), value = T))) %>%
  as_tibble() %>%
  gather(pathway, score, -c(1:4)) %>% 
  left_join(meta_tbl, by = "sample") %>%
  filter(sort_short == "CD45-", therapy == "pre-Rx") %>% 
  mutate(pathway = str_remove_all(pathway, "\\.pathway")) %>% 
  mutate(cluster_label = str_remove_all(cluster_label, "\\.cell"))

cut_value <- 2
pathway_summary_wrapper <- . %>% 
  summarise(mean_score = mean(score),
            median_score = median(score)) %>% 
  mutate(median_cut = ifelse(median_score > cut_value, cut_value, 
                             ifelse(median_score < -cut_value, -cut_value, 
                                    median_score))) %>% 
  mutate(mean_cut = ifelse(mean_score > cut_value, cut_value, 
                           ifelse(mean_score < -cut_value, -cut_value, 
                                  mean_score)))


# plot_data_summary_patient <- plot_data %>% 
#   group_by(patient_id_short, consensus_signature, cluster_label, 
#            pathway, tumor_supersite) %>% 
#   pathway_summary_wrapper
# 
# plot_data_summary_mutsig <- plot_data %>% 
#   group_by(consensus_signature, pathway) %>% 
#   pathway_summary_wrapper
# 
# plot_data_summary_mutsig_cluster <- plot_data %>% 
#   group_by(consensus_signature, cluster_label, pathway) %>% 
#   pathway_summary_wrapper

plot_data_summary_cluster <- plot_data %>%
  group_by(cluster_label, pathway) %>%
  pathway_summary_wrapper

plot_data_summary_mutsig_patient <- plot_data %>% 
  group_by(consensus_signature, patient_id_short, pathway) %>% 
  pathway_summary_wrapper


```

```{r chunk_100, fig.width=15, fig.height=10}

common_heat_layers <- list(
  scale_fill_gradient2(low = scales::muted("blue"), high = scales::muted("red"), 
                       na.value = "grey10", 
                       breaks = c(-cut_value, 0, cut_value), 
                       labels = c(paste0("≤-", cut_value), "0", paste0("≥", cut_value)),
                       limits = c(-cut_value, cut_value)),
  theme(axis.text.x = element_text(angle = 60, hjust = 1, vjust = 1),
        axis.ticks = element_blank(),
        axis.line = element_blank(),
        axis.title = element_blank(),
        plot.margin = margin(0, 0, 0, 0))
)

# ggplot(plot_data_summary_patient) + 
#   geom_tile(aes(cluster_label, patient_id_short, fill = median_cut)) +
#   facet_grid(consensus_signature~pathway, scales = "free", space = "free") +
#   common_heat_layers
#   
# ggplot(plot_data_summary_mutsig_cluster) + 
#   geom_tile(aes(pathway, cluster_label, fill = median_cut)) +
#   facet_grid(~consensus_signature, scales = "free", space = "free") +
#   common_heat_layers   
# 
# ggplot(plot_data_summary_mutsig) + 
#   geom_tile(aes(consensus_signature, pathway, fill = median_score)) +
#   common_heat_layers

pw_plot1 <- ggplot(mutate(plot_data_summary_cluster, facet_helper = "")) +
  geom_tile(aes(cluster_label, pathway, fill = mean_score)) +
  common_heat_layers +
  facet_grid(~facet_helper, scales = "free", space = "free") + 
  labs(x = "Cluster", y = "Pathway", fill = "Mean\nPROGENy\nscore") +
  scale_fill_gradient2(low = scales::muted("blue"), high = scales::muted("red"), 
                       na.value = "grey10", 
                       breaks = c(-cut_value, 0, cut_value), 
                       labels = c(paste0("≤-", cut_value), "0", paste0("≥", cut_value))) +
  theme(axis.text.x = element_blank())

pw_plot1_anno <- ggplot(mutate(plot_data_summary_cluster, facet_helper = "")) +
  geom_tile(aes(cluster_label, facet_helper, fill = cluster_label)) +
  common_heat_layers + 
  scale_fill_manual(values = clrs$cluster_label$Ovarian.cancer.cell %>% setNames(str_remove_all(names(.), "\\.cell"))) +
  facet_grid(~facet_helper, scales = "free", space = "free") +
  theme(axis.text.y = element_blank(),
        strip.text = element_blank()) +
  guides(fill = F)
  
pw_plot2 <- ggplot(plot_data_summary_mutsig_patient) + 
  geom_tile(aes(patient_id_short, pathway, fill = mean_cut)) +
  facet_grid(~consensus_signature, scales = "free", space = "free") + 
  common_heat_layers +
  labs(x = "Patient", y = "", fill = "Mean\nPROGENy\nscore") +
  theme(axis.text.x = element_blank())

pw_plot2_anno <- ggplot(mutate(plot_data_summary_mutsig_patient, facet_helper = "")) +
  geom_tile(aes(patient_id_short, facet_helper, fill = consensus_signature)) +
  common_heat_layers + 
  scale_fill_manual(values = clrs$consensus_signature) +
  facet_grid(~consensus_signature, scales = "free", space = "free") + 
  theme(axis.text.y = element_blank(),
        strip.text = element_blank()) +
  guides(fill = F)

pw_grid <- plot_grid(pw_plot1 + guides(fill = F), ggdraw(), pw_plot2 + guides(fill = F), 
                     pw_plot1_anno, ggdraw(), pw_plot2_anno,
                     nrow = 2, align = "v", axis = "lrtb",
                     rel_widths = c(0.25, 0.05, 0.7), rel_heights = c(0.7, 0.3))

pw_boxplot <- filter(plot_data, pathway == "JAK.STAT") %>%
  mutate(patient_id_short = ordered(patient_id_short, levels = unique(arrange(plot_data_summary_mutsig_patient, pathway != "JAK.STAT", median_score)$patient_id_short))) %>% 
  ggplot() +
  geom_boxplot(aes(patient_id_short, score, color = consensus_signature)) +
  scale_color_manual(values = clrs$consensus_signature) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1, vjust = 1)) +
  labs(x = "Patient", y = "JAK/STAT pathway\nPROGENy score")

pw_grid_full <- ggdraw() +
  draw_plot(pw_grid, x = 0, y = 0.5, width = 0.9, height = 0.5) +
  draw_grob(get_legend(pw_plot2), x = 0.92, y = 0.25) +
  draw_plot(pw_boxplot + guides(color = F), x = 0, y = 0, width = 0.65, height = 0.45)

pw_grid_full

ggsave("_fig/003_cancer_cell/003_pathway_heatmap.pdf", pw_grid_full, 
       width = 15, height = 10)

```

# session info 

```{r chunk_999}

devtools::session_info()

```

