---
title: "Interferome"
author: "Florian Uhlitz"
date: "`r Sys.Date()`"
output: 
  html_document: 
    df_print: kable
    number_sections: yes
    toc: yes
    toc_float: true
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = F)

```

```{r chunk_010}

library(magrittr)
library(tidyverse)
library(readxl)
library(cowplot)
library(colorblindr)
library(viridis)

```

# Interferome data

```{r chunk_020}

ifn_tbl <- read_tsv("/work/shah/uhlitzf/data/global/interferome.tsv", skip = 18) %>% 
  select(1:5) %>% 
  setNames(c("data_id", "log2fc", "ifn_type", "treatment_duration", "gene"))

ifn_top <- ifn_tbl %>% 
  mutate(regulation = ifelse(log2fc > 5, "up", ifelse(log2fc < -5, "dn", "weak"))) %>% 
  group_by(gene, ifn_type, regulation) %>% 
  tally %>% 
  # filter(n > 10) %>% 
  ungroup %>% 
  arrange(ifn_type, desc(regulation), desc(n)) %>% 
  group_by(ifn_type, regulation) %>% 
  slice(1:10)

logcut <- 20
  
ifn_tbl %>% 
  distinct(data_id, gene, ifn_type, .keep_all = T) %>% 
  mutate(log2fc_cut = ifelse(log2fc > logcut, logcut, log2fc)) %>% 
  mutate(log2fc_cut = ifelse(log2fc_cut < -logcut, -logcut, log2fc_cut)) %>% 
  mutate(data_id = as.factor(data_id)) %>% 
  filter(gene %in% unique(ifn_top$gene)) %>% 
  ggplot(aes(data_id, gene, fill = log2fc_cut)) + 
  geom_tile() + 
  scale_fill_gradient2() + 
  facet_grid(~ifn_type, scales = "free", space = "free") +
  theme_void()

```

